# Generated by Django 4.2.4 on 2023-08-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
