# Generated by Django 4.2.4 on 2023-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_update_at_trainer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='departament',
            field=models.CharField(choices=[('backend', 'BACKEND'), ('frontend', 'FRONTEND'), ('network', 'NETWORK')], max_length=8),
        ),
    ]
