# Generated by Django 4.2.4 on 2023-08-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='departament',
            field=models.CharField(choices=[('Backend', 'BACKEND'), ('Frontend', 'FRONTEND'), ('Network', 'NETWORK')], max_length=8),
        ),
    ]
