# Generated by Django 4.2.4 on 2023-08-23 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_historystudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historystudent',
            name='user',
        ),
        migrations.AddField(
            model_name='historystudent',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
