# Generated by Django 4.2.4 on 2023-08-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_historystudent_user_historystudent_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historystudent',
            old_name='userid',
            new_name='user',
        ),
    ]
