# Generated by Django 4.2.4 on 2023-08-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pret',
            field=models.FloatField(default=0.0),
        ),
    ]
